name: Build Python Package

on:
  push:
    tags:
      - 'v*'  # Runs only when pushing version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required so Git tags are available

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build hatch hatch-vcs build

      - name: Build project
        run: |
          python -m build
          
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/structures-*.whl
          asset_name: structures-${{ github.ref_name }}.whl
          asset_content_type: application/octet-stream

      - name: Upload source distribution
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/structures-*.tar.gz
          asset_name: structures-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
